name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose        
    - name: Install cargo-rdme
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-rdme
        version: "1.0"
    - name: Verify README updated
      continue-on-error: true
      id: readme_updated
      run: |
        cargo rdme --check
        echo "README_CHANGED=$?" >> $GITHUB_OUTPUT
    - name: Run cargo-rdme
      if: failure()
      run: cargo rdme
    - name: Open PR if README updated.
      if: success()
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
            README.md
