name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose        
    - name: Install cargo-sync-readme
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-sync-readme
        version: "1.1"
    - name: Run cargo-sync-readme
      run: cargo sync-readme
    - name: Verify README updated
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files
      with:
        files: |
          README.md

    - name: Open PR if README updated.
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: echo "README UPDATED"
