name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose        
    - name: Install cargo-rdme
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-rdme
        version: "1.1"
    - name: Verify README updated
      id: readme_updated
      run: echo "::set-output name=README_CHANGED::$(cargo rdme --check)"
    - name: Run cargo-rdme
      if: steps.readme_updated.outputs.README_CHANGES == '3'
      run: cargo rdme
    - name: Open PR if README updated.
      if: steps.readme_updated.outputs.README_CHANGES == '3'
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
            README.md
